import { ReactNode } from 'react';
import type { Metadata } from "next";
import { Providers } from '@/components/Providers';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children}: Readonly<{
  children: ReactNode;
}>) => (
    <html lang="en" suppressHydrationWarning>
      <body>
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  );

export default RootLayout;
